apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  ports:
  - port: 9400
    name: user-service
    targetPort: 9000
  type: ClusterIP
  selector:
    app: user-service