apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
  - port: 8080
    name: keycloak
    targetPort: 8080
  type: ClusterIP
  selector:
    app: keycloak