apiVersion: v1
kind: Service
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  ports:
  - port: 9200
    name: movie-service
    targetPort: 9000
  type: ClusterIP
  selector:
    app: movie-service