apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: miclfix-standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: micflix-pv
spec:
  storageClassName: "miclfix-standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
