apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service-deployment
  labels:
    app: movie-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: movie-service
        image: mickeykrekels/my-projects:Micflix-Movie-Service
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"            
        env:
        - name: MDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: movie-service
              key: MDB_USERNAME

        - name: MDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: movie-service
              key: MDB_PASSWORD
 
        - name: MDB_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: movie-service
              key: MDB_CLUSTER

        - name: MDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: movie-service
              key: MDB_DATABASE             