apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred
      containers:
      - name: user-service
        image: mickeykrekels/my-projects:Micflix-User-Service
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"            
        env:
        - name: MDB_USERNAME
          valueFrom:
            secretKeyRef:
              name: user-service
              key: MDB_USERNAME

        - name: MDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-service
              key: MDB_PASSWORD

        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: user-service
              key: RABBITMQ_URL   

        - name: MDB_CLUSTER
          valueFrom:
            configMapKeyRef:
              name: user-service
              key: MDB_CLUSTER

        - name: MDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: user-service
              key: MDB_DATABASE
